[Apps]

    [Apps."Apartment-20 vSphere"]
    url="http://192.168.68.132/ui/"
    tag="wmware"
    enable_api=false
    icon="https://p7.hiclipart.com/preview/896/165/228/vmware-vsphere-vmware-esxi-virtual-machine-host-high-definition.jpg"

    [Apps."BitBucket"]
    url="http://192.168.68.141:7990/"
    tag="bb"
    enable_api=false
    icon="https://cdn.worldvectorlogo.com/logos/bitbucket-icon.svg"

    [Apps."Central-Perk vSphere"]
    url="https://192.168.68.131/ui/"
    tag="N/A"
    enable_api=false
    icon="https://p7.hiclipart.com/preview/896/165/228/vmware-vsphere-vmware-esxi-virtual-machine-host-high-definition.jpg"

    [Apps."Cisco"]
    url="http://192.168.68.206"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Code-Server"]
    url="http://ross.briddle.local:8080"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Confluence"]
    url="https://confluence.briddle.party"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Deluge"]
    url="http://pi.briddle.local:8112/"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."ESPhome"]
    url="http://192.168.68.67:6052/"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."EdgeRouter X"]
    url="https://192.168.68.1"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Ghost"]
    url="https://blog.briddle.party/ghost"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."GitHub"]
    url="https://github.com/declanthebritton"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."GitLab"]
    url="https://git.briddle.party"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Grafana"]
    url="http://192.168.68.197:3000/"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."HDHomeRun"]
    url="http://192.168.68.128"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."HLPT Admin"]
    url="https://www.hlpt.co.uk/admin/#/login"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."HomeAssistant"]
    url="http://192.168.68.67:8123/"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Jira"]
    url="https://jira.briddle.party/"
    tag="N/A"
    enable_api=false
    icon="https://www.solarwinds.com/-/media/solarwinds/swdcv2/licensed-products/service-desk/integrations/sd-integrations-logo-jira.ashx?rev=701fbaa7f8ac4ae08e0406c8984c43e7&hash=75D4F04DE99B88DE7B2C4193F0616F1F"

    [Apps."Moondance vSphere"]
    url="https://192.168.68.123/ui"
    tag="N/A"
    enable_api=false
    icon="https://p7.hiclipart.com/preview/896/165/228/vmware-vsphere-vmware-esxi-virtual-machine-host-high-definition.jpg"

    [Apps."Netlify"]
    url="https://app.netlify.com/teams/declanthebritton/sites"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Nextcloud"]
    url="http://192.168.68.198:8282/"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."NginxProxyManager"]
    url="http://192.168.68.124:81/"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Nzbget"]
    url="http://142.4.208.113:6789/"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Ombi"]
    url="https://request.briddle.party/"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Plex"]
    url="http://chandler.briddle.local:32400/web/index.html"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Portainer"]
    url="http://joey.briddle.local:9000"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Prometheus"]
    url="http://192.168.68.197:9090/"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Radarr"]
    url="http://142.4.208.113:7878/"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Sonarr"]
    url="http://142.4.208.113:8989/"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Todoist"]
    url="https://todoist.com/app"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Tautulli"]
    url="http://joey.briddle.local:32772/home"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."Truenas"]
    url="http://192.168.68.198/ui"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."UNMS"]
    url="https://192.168.68.34"
    tag="N/A"
    enable_api=false
    icon=""

    [Apps."VMware vCenter"]
    url="https://rachel.briddle.local"
    tag="N/A"
    enable_api=false
    icon="https://p7.hiclipart.com/preview/896/165/228/vmware-vsphere-vmware-esxi-virtual-machine-host-high-definition.jpg"

    [Apps."kimsufi"]
    url="https://www.kimsufi.com/en/manager"
    tag="N/A"
    enable_api=false
    icon=""